package com.softline.client.bima;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IWsSystemService", targetNamespace = "http://webService.softline.com/")
public interface IWsSystemService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getGsProcess02", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGsProcess02")
	@ResponseWrapper(localName = "getGsProcess02Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGsProcess02Response")
	public String getGsProcess02(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsers03", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsers03")
	@ResponseWrapper(localName = "getUsers03Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsers03Response")
	public String getUsers03(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllPerson02", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetAllPerson02")
	@ResponseWrapper(localName = "getAllPerson02Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetAllPerson02Response")
	public String getAllPerson02(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllPerson01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetAllPerson01")
	@ResponseWrapper(localName = "getAllPerson01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetAllPerson01Response")
	public String getAllPerson01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAbnormalmessage01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetAbnormalmessage01")
	@ResponseWrapper(localName = "getAbnormalmessage01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetAbnormalmessage01Response")
	public String getAbnormalmessage01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUserspostrecord01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUserspostrecord01")
	@ResponseWrapper(localName = "getUserspostrecord01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUserspostrecord01Response")
	public String getUserspostrecord01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMajorProperty", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetMajorProperty")
	@ResponseWrapper(localName = "getMajorPropertyResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetMajorPropertyResponse")
	public String getMajorProperty(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getHhOrganInfo01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetHhOrganInfo01")
	@ResponseWrapper(localName = "getHhOrganInfo01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetHhOrganInfo01Response")
	public String getHhOrganInfo01();

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrganInfoTree", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetOrganInfoTree")
	@ResponseWrapper(localName = "getOrganInfoTreeResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetOrganInfoTreeResponse")
	public String getOrganInfoTree();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getManagerCompare01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetManagerCompare01")
	@ResponseWrapper(localName = "getManagerCompare01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetManagerCompare01Response")
	public String getManagerCompare01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getGsProcess01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGsProcess01")
	@ResponseWrapper(localName = "getGsProcess01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGsProcess01Response")
	public String getGsProcess01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.softline.client.bima.HhUsers
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsersEntity01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsersEntity01")
	@ResponseWrapper(localName = "getUsersEntity01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsersEntity01Response")
	public HhUsers getUsersEntity01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getTop", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetTop")
	@ResponseWrapper(localName = "getTopResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetTopResponse")
	public String getTop(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getisPledge", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetisPledge")
	@ResponseWrapper(localName = "getisPledgeResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetisPledgeResponse")
	public String getisPledge();

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMajorPropertyName", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetMajorPropertyName")
	@ResponseWrapper(localName = "getMajorPropertyNameResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetMajorPropertyNameResponse")
	public String getMajorPropertyName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsers02", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsers02")
	@ResponseWrapper(localName = "getUsers02Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsers02Response")
	public String getUsers02(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getCompanyTree", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetCompanyTree")
	@ResponseWrapper(localName = "getCompanyTreeResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetCompanyTreeResponse")
	public String getCompanyTree();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getGsBrand01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGsBrand01")
	@ResponseWrapper(localName = "getGsBrand01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGsBrand01Response")
	public String getGsBrand01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getGSCompanyData", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGSCompanyData")
	@ResponseWrapper(localName = "getGSCompanyDataResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetGSCompanyDataResponse")
	public String getGSCompanyData();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsers01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsers01")
	@ResponseWrapper(localName = "getUsers01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsers01Response")
	public String getUsers01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOriginalValue", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetOriginalValue")
	@ResponseWrapper(localName = "getOriginalValueResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetOriginalValueResponse")
	public String getOriginalValue(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUserscompany01", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUserscompany01")
	@ResponseWrapper(localName = "getUserscompany01Response", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUserscompany01Response")
	public String getUserscompany01(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getischeckid", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.Getischeckid")
	@ResponseWrapper(localName = "getischeckidResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetischeckidResponse")
	public String getischeckid();

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getNode", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetNode")
	@ResponseWrapper(localName = "getNodeResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetNodeResponse")
	public String getNode(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUsersbim", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsersbim")
	@ResponseWrapper(localName = "getUsersbimResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetUsersbimResponse")
	public String getUsersbim(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getuseStatus", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetuseStatus")
	@ResponseWrapper(localName = "getuseStatusResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.bima.GetuseStatusResponse")
	public String getuseStatus();

}
