package com.softline.client.bima;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WsSystemServiceService service = new WsSystemServiceService();
 * IWsSystemService portType = service.getWsSystemServicePort();
 * portType.getGsProcess02(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WsSystemServiceService", targetNamespace = "http://impl.webService.softline.com/", wsdlLocation = "http://10.123.32.74:8080/hhang_web/webService/wsSystemService?wsdl")
public class WsSystemServiceService extends Service {

	private final static URL WSSYSTEMSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.softline.client.bima.WsSystemServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.softline.client.bima.WsSystemServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.123.32.74:8080/hhang_web/webService/wsSystemService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.123.32.74:8080/hhang_web/webService/wsSystemService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSSYSTEMSERVICESERVICE_WSDL_LOCATION = url;
	}

	public WsSystemServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WsSystemServiceService() {
		super(WSSYSTEMSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://impl.webService.softline.com/",
				"WsSystemServiceService"));
	}

	/**
	 * 
	 * @return returns IWsSystemService
	 */
	@WebEndpoint(name = "WsSystemServicePort")
	public IWsSystemService getWsSystemServicePort() {
		return super.getPort(new QName("http://impl.webService.softline.com/",
				"WsSystemServicePort"), IWsSystemService.class);
	}

}
