package com.softline.client.sso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IAuthorityService", targetNamespace = "http://webService.softline.com/")
public interface IAuthorityService {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.softline.client.sso.SsoCheckResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "cancelLogin", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.sso.CancelLogin")
	@ResponseWrapper(localName = "cancelLoginResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.sso.CancelLoginResponse")
	public SsoCheckResult cancelLogin(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns com.softline.client.sso.SsoCheckResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addNewLogin", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.sso.AddNewLogin")
	@ResponseWrapper(localName = "addNewLoginResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.sso.AddNewLoginResponse")
	public SsoCheckResult addNewLogin(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns com.softline.client.sso.SsoCheckResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkLogin", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.sso.CheckLogin")
	@ResponseWrapper(localName = "checkLoginResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.sso.CheckLoginResponse")
	public SsoCheckResult checkLogin(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

}
