package com.softline.client.show;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IShowWebservice", targetNamespace = "http://webService.softline.com/")
public interface IShowWebservice {

	/**
	 * 
	 * @return returns java.util.List<com.softline.client.show.DefTask>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllDefTaskDEF", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.GetAllDefTaskDEF")
	@ResponseWrapper(localName = "getAllDefTaskDEFResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.GetAllDefTaskDEFResponse")
	public List<DefTask> getAllDefTaskDEF();

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns com.softline.client.show.DefTask
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDefTaskDEF", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.GetDefTaskDEF")
	@ResponseWrapper(localName = "getDefTaskDEFResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.GetDefTaskDEFResponse")
	public DefTask getDefTaskDEF(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "alarmCount", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.AlarmCount")
	@ResponseWrapper(localName = "alarmCountResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.AlarmCountResponse")
	public String alarmCount();

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod(operationName = "ModifyDefTask")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "ModifyDefTask", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.ModifyDefTask")
	@ResponseWrapper(localName = "ModifyDefTaskResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.ModifyDefTaskResponse")
	public boolean modifyDefTask(
			@WebParam(name = "arg0", targetNamespace = "") DefTask arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "alarmTimeOutCount", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.AlarmTimeOutCount")
	@ResponseWrapper(localName = "alarmTimeOutCountResponse", targetNamespace = "http://webService.softline.com/", className = "com.softline.client.show.AlarmTimeOutCountResponse")
	public String alarmTimeOutCount();

}
